#include "graphics.h"
#include "gba.h"
// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
//#include "images/garbage.h"
#include "images/begin0.h"
#include "images/hedwig.h"
#include "images/lose.h"
#include "images/win.h"
#include "images/and.h"
#include "images/or.h"
#include "images/not.h"
#include "images/down.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);
void drawRectangle(int row, int col, int width, int height, const u16 *image)
{
	const u16 *pixel = image;
	for (int x = 0; x < height; x++) {
    	for (int y = 0; y < width; y++) {
			u16 color = *(pixel + OFFSET(row+x, col+y, 240));
	    	setPixel(col + y, row + x, color);	
		}
    }
}


// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
	fillScreenDMA(WHITE);
	drawImageDMA(60, 160, 56, 80, hedwig);
	Gate current = state->fallingGate;
	//unsigned short ids[4] = {and, or, not, down};
	int curid = current.id;
	//const unsigned short cur = state->ids[curid];
	if (curid == 0) drawImageDMA(current.row,current.col,40,40,and);
	if (curid == 1) drawImageDMA(current.row,current.col,40,40,not);
	if (curid == 2) drawImageDMA(current.row,current.col,40,40,or);
	if (curid == 3) drawImageDMA(current.row,current.col,40,40,down);
    //UNUSED(state);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
	Gate current = state->fallingGate;

	drawRectDMA(current.row,current.col,40,40,WHITE);
    UNUSED(state);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
	Gate current = state->fallingGate;
	int curid = current.id;
	if (curid == 0) drawImageDMA(current.row,current.col,40,40,and);
	if (curid == 1) drawImageDMA(current.row,current.col,40,40,not);
	if (curid == 2) drawImageDMA(current.row,current.col,40,40,or);
	if (curid == 3) drawImageDMA(current.row,current.col,40,40,down);
    //UNUSED(state);
}
