#include "gba.h"
#include "logic.h"
#include "graphics.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
//#include "images/garbage.h"
#include "images/hogwarts.h"
#include "images/begin0.h"
#include "images/apple.h"
#include "images/hedwig.h"
#include "images/parchment.h"

#include <stdio.h>
#include <stdlib.h>

// AppState enum definition
typedef enum {
    // TA-TODO: Add any additional states you need for your app.
    START,
    START_NODRAW,
	APP_FEED,
	DISPLAY_LETTER,
    APP_INIT,
    APP,
    APP_EXIT,
    APP_EXIT_NODRAW,
} GBAState;

int main(void) {
    // TA-TODO: Manipulate REG_DISPCNT here to set Mode 3.
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

	//parameters for apple
	int xApple = 40;
	int yApple = 180;
	int appleSize = 15;

    while(1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;	
		waitForVBlank();
		if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
			state = START;
		}

        // TA-TODO: Manipulate the state machine below as needed.
        switch(state) {
        case START:
            // Wait for VBlank
            waitForVBlank();

            // TA-TODO: Draw the start state here.
			drawFullScreenImageDMA(hogwarts);

            state = START_NODRAW;
            break;
        case START_NODRAW:
            // TA-TODO: Check for a button press here to start the app.
            // Start the app by switching the state to APP_INIT.
			//if (KEY_DOWN(BUTTON_A, BUTTONS) && !KEY_DOWN(previousButtons, BUTTONS)) {

			if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
				//printf("what happened?\n");
				drawFullScreenImageDMA(begin0);
				drawImageDMA(xApple, yApple, appleSize, appleSize, apple);
				state = APP_FEED;
			}
			break;
		case APP_FEED:
			if (xApple <= 120 && xApple >= 60 && yApple <= 100 && yApple >= 70) {
				state = DISPLAY_LETTER;
				break;
			}
			if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
		   		yApple+=2; 
				drawFullScreenImageDMA(begin0);
				drawImageDMA(xApple, yApple, appleSize, appleSize, apple);
				break;
			}
			if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
		   		yApple-=2;
				drawFullScreenImageDMA(begin0);
				drawImageDMA(xApple, yApple, appleSize, appleSize, apple);
				break;
			}
			if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
		    	xApple-=2;
				drawFullScreenImageDMA(begin0);
				drawImageDMA(xApple, yApple, appleSize, appleSize, apple);
				break;
			}
			if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
		    	xApple+=2; 
				drawFullScreenImageDMA(begin0);
				drawImageDMA(xApple, yApple, appleSize, appleSize, apple);
			}
			//TODO: put something here to wait for a screen refresh before continuing
			
			//feedApple(xApple, yApple);
			break;
		case DISPLAY_LETTER:
			
			waitForVBlank();
			fillScreenDMA(WHITE);
			drawImageDMA(5, 5, 150, 150, parchment);
			drawImageDMA(60, 160, 56, 80, hedwig);
			char *letter = "Congrats!";
			drawString(40, 40, letter, BLACK);
			state = APP_INIT;
			break;
            
        case APP_INIT:
            // Initialize the app. Switch to the APP state.
			//waitForVBlank();
			//drawFullScreenImageDMA(begin0);
            initializeAppState(&currentAppState);

            // Draw the initial state of the app
            fullDrawAppState(&currentAppState);

            state = APP;
            break;
        case APP:
            // Process the app for one frame, store the next state
            nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);

            // Wait for VBlank before we do any drawing.
            waitForVBlank();

            // Undraw the previous state
            undrawAppState(&currentAppState);

            // Draw the current state
            drawAppState(&nextAppState);

            // Now set the current state as the next state for the next iter.
            currentAppState = nextAppState;

            // Check if the app is exiting. If it is, then go to the exit state.
            if (nextAppState.gameOver) state = APP_EXIT;

            break;
        case APP_EXIT:
            // Wait for VBlank
            waitForVBlank();

            // TA-TODO: Draw the exit / gameover screen

            state = APP_EXIT_NODRAW;
            break;
        case APP_EXIT_NODRAW:
            // TA-TODO: Check for a button press here to go back to the start screen

            break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
